### ISSUE TITLE
Does not work in sandboxed solutions

### ISSUE THREAD

**Issue by luisvsilva** [joaope/CAMLBuilder#1]
All it takes is to add an attribute to the assembly, I will do that and submit a pull request

By the way awesome work, it is the only CAML helper that is easy to change in order to work in Sandboxed solutions.

Bom trabalho mano grande abraco daqui das Australias :)

**Comment by joaope** [comment]
Fixed by your pull request.

Obrigado pela ajuda! Abraço :)
