### ISSUE TITLE
TodayValue class inserts Offset attribute and the query's results are different if OffsetDays is replaced instead

### ISSUE THREAD

**Issue by gsalatino** [joaope/camlbuilder#11]
The GetCamlValue method of TodayValue class inserts the Offset attribute. When it's tested with a negative offset it doesn't return the expected set of list items.

The workaround applied was to replace the Offset attribute with OffsetDays when generating the CAML Xml.

**Comment by joaope** [comment]
I think you're right. Microsoft refers to the attribute has [Offset](https://msdn.microsoft.com/en-us/library/office/ms460496.aspx#Anchor_0) tho but the consensus [here](https://sharepoint.stackexchange.com/questions/135968/what-is-the-difference-between-caml-offset-and-offsetdays) is that the documentation is wrong and it should be _OffsetDays_.

I'm fixing it to be _OffsetDays_.

**Comment by gsalatino** [comment]
Thank you very much for your the quick response! The fix works great!
