### ISSUE TITLE
FieldReference class inserts Ascending attribute without preceding whitespace

### ISSUE THREAD

**Issue by gsalatino** [joaope/camlbuilder#12]
The GetCaml method of the FieldReference (ln:209) class inserts the Ascending attribute without the preceding whitespace and result in a malformed Xml.

**Comment by joaope** [comment]
Thanks for all the bug reporting. Really appreciate it. I'll be publishing a new package to nuget shortly.

Cheers

**Comment by gsalatino** [comment]
Thanks to you for such a nice and useful package!

**Comment by gsalatino** [comment]
Thank you very much for your the quick response! The fix works great!
