### ISSUE TITLE
Too much new lines

### ISSUE THREAD

**Issue by KoalaBear84** [joaope/camlbuilder#14]
I was trying to implement camlbuilder into my project and got stuck on this.

Code:
```
Query getCustomerSiteByTitleQuery = Query.Build(
  Operator.Equal("Title", CamlBuilder.ValueType.Text, "CustomerSiteName")
);
string viewXml = $@"<View>{getCustomerSiteByTitleQuery.GetCaml()}</View>";
```

Resulting query:
```
<View>
<Query>
    
<Where>
    
<Eq>
    <FieldRef Name='Title'/>
    <Value Type='Text'>
CustomerSiteName
</Value>

</Eq>

</Where>
    
    
</Query>
</View>
```

Because of the value has a new line in front and behind it, it does not match any results. 

Query should look like (no new line in Value tag):
```
<View>
  <Query>
    <Where>
      <Eq>
        <FieldRef Name='Title'/>
        <Value Type='Text'>CustomerSiteName</Value>
      </Eq>
    </Where>
  </Query>
</View>
```

Also I have to add <View> to it myself, but that is not a big issue.

**Comment by joaope** [comment]
Just published a new package in NuGet fixing this. Thanks for reporting the issue.

**Comment by KoalaBear84** [comment]
Great work! Will try it Wednesday 👍

**Comment by KoalaBear84** [comment]
Had some extra time and tested it. Now it works 👍
